set_property SRC_FILE_INFO {cfile:{c:/Users/Nguyen Ha Hai/axi4-system-suite/synthesis/scripts/vivado/axi4_system_sv_kv260/axi4_system_sv_kv260.gen/sources_1/bd/design_1/ip/design_1_axi_slave_bridge_s3_0/src/axi_interconnect.xdc} rfile:../../../axi4_system_sv_kv260.gen/sources_1/bd/design_1/ip/design_1_axi_slave_bridge_s3_0/src/axi_interconnect.xdc id:1 order:EARLY scoped_inst:inst} [current_design]
current_instance inst
set_property src_info {type:SCOPED_XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock ACLK -max 2.0 [get_ports M0_AWADDR*]
set_property src_info {type:SCOPED_XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock ACLK -min 0.5 [get_ports M0_AWADDR*]
set_property src_info {type:SCOPED_XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock ACLK -max 2.0 [get_ports M0_ARADDR*]
set_property src_info {type:SCOPED_XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock ACLK -min 0.5 [get_ports M0_ARADDR*]
set_property src_info {type:SCOPED_XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock ACLK -max 2.0 [get_ports M0_WDATA*]
set_property src_info {type:SCOPED_XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock ACLK -min 0.5 [get_ports M0_WDATA*]
set_property src_info {type:SCOPED_XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock ACLK -max 2.0 [get_ports M0_AWVALID]
set_property src_info {type:SCOPED_XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock ACLK -min 0.5 [get_ports M0_AWVALID]
set_property src_info {type:SCOPED_XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock ACLK -max 2.0 [get_ports M0_ARVALID]
set_property src_info {type:SCOPED_XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock ACLK -min 0.5 [get_ports M0_ARVALID]
set_property src_info {type:SCOPED_XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock ACLK -max 2.0 [get_ports M0_WVALID]
set_property src_info {type:SCOPED_XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock ACLK -min 0.5 [get_ports M0_WVALID]
set_property src_info {type:SCOPED_XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock ACLK -max 2.0 [get_ports M0_BREADY]
set_property src_info {type:SCOPED_XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock ACLK -min 0.5 [get_ports M0_BREADY]
set_property src_info {type:SCOPED_XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock ACLK -max 2.0 [get_ports M0_RREADY]
set_property src_info {type:SCOPED_XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock ACLK -min 0.5 [get_ports M0_RREADY]
set_property src_info {type:SCOPED_XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock ACLK -max 2.0 [get_ports M1_AWADDR*]
set_property src_info {type:SCOPED_XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock ACLK -min 0.5 [get_ports M1_AWADDR*]
set_property src_info {type:SCOPED_XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock ACLK -max 2.0 [get_ports M1_ARADDR*]
set_property src_info {type:SCOPED_XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock ACLK -min 0.5 [get_ports M1_ARADDR*]
set_property src_info {type:SCOPED_XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock ACLK -max 2.0 [get_ports M1_WDATA*]
set_property src_info {type:SCOPED_XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock ACLK -min 0.5 [get_ports M1_WDATA*]
set_property src_info {type:SCOPED_XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock ACLK -max 2.0 [get_ports M1_AWVALID]
set_property src_info {type:SCOPED_XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock ACLK -min 0.5 [get_ports M1_AWVALID]
set_property src_info {type:SCOPED_XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock ACLK -max 2.0 [get_ports M1_ARVALID]
set_property src_info {type:SCOPED_XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock ACLK -min 0.5 [get_ports M1_ARVALID]
set_property src_info {type:SCOPED_XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock ACLK -max 2.0 [get_ports M1_WVALID]
set_property src_info {type:SCOPED_XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock ACLK -min 0.5 [get_ports M1_WVALID]
set_property src_info {type:SCOPED_XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock ACLK -max 2.0 [get_ports M1_BREADY]
set_property src_info {type:SCOPED_XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock ACLK -min 0.5 [get_ports M1_BREADY]
set_property src_info {type:SCOPED_XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock ACLK -max 2.0 [get_ports M1_RREADY]
set_property src_info {type:SCOPED_XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock ACLK -min 0.5 [get_ports M1_RREADY]
set_property src_info {type:SCOPED_XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -max 2.0 [get_ports S0_AWADDR*]
set_property src_info {type:SCOPED_XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -min 0.5 [get_ports S0_AWADDR*]
set_property src_info {type:SCOPED_XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -max 2.0 [get_ports S0_ARADDR*]
set_property src_info {type:SCOPED_XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -min 0.5 [get_ports S0_ARADDR*]
set_property src_info {type:SCOPED_XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -max 2.0 [get_ports S0_WDATA*]
set_property src_info {type:SCOPED_XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -min 0.5 [get_ports S0_WDATA*]
set_property src_info {type:SCOPED_XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -max 2.0 [get_ports S0_AWVALID]
set_property src_info {type:SCOPED_XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -min 0.5 [get_ports S0_AWVALID]
set_property src_info {type:SCOPED_XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -max 2.0 [get_ports S0_ARVALID]
set_property src_info {type:SCOPED_XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -min 0.5 [get_ports S0_ARVALID]
set_property src_info {type:SCOPED_XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -max 2.0 [get_ports S0_WVALID]
set_property src_info {type:SCOPED_XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -min 0.5 [get_ports S0_WVALID]
set_property src_info {type:SCOPED_XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -max 2.0 [get_ports S0_BREADY]
set_property src_info {type:SCOPED_XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -min 0.5 [get_ports S0_BREADY]
set_property src_info {type:SCOPED_XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -max 2.0 [get_ports S0_RREADY]
set_property src_info {type:SCOPED_XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -min 0.5 [get_ports S0_RREADY]
set_property src_info {type:SCOPED_XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -max 2.0 [get_ports S1_AWADDR*]
set_property src_info {type:SCOPED_XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -min 0.5 [get_ports S1_AWADDR*]
set_property src_info {type:SCOPED_XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -max 2.0 [get_ports S1_ARADDR*]
set_property src_info {type:SCOPED_XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -min 0.5 [get_ports S1_ARADDR*]
set_property src_info {type:SCOPED_XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -max 2.0 [get_ports S1_WDATA*]
set_property src_info {type:SCOPED_XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -min 0.5 [get_ports S1_WDATA*]
set_property src_info {type:SCOPED_XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -max 2.0 [get_ports S1_AWVALID]
set_property src_info {type:SCOPED_XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -min 0.5 [get_ports S1_AWVALID]
set_property src_info {type:SCOPED_XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -max 2.0 [get_ports S1_ARVALID]
set_property src_info {type:SCOPED_XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -min 0.5 [get_ports S1_ARVALID]
set_property src_info {type:SCOPED_XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -max 2.0 [get_ports S1_WVALID]
set_property src_info {type:SCOPED_XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -min 0.5 [get_ports S1_WVALID]
set_property src_info {type:SCOPED_XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -max 2.0 [get_ports S1_BREADY]
set_property src_info {type:SCOPED_XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -min 0.5 [get_ports S1_BREADY]
set_property src_info {type:SCOPED_XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -max 2.0 [get_ports S1_RREADY]
set_property src_info {type:SCOPED_XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -min 0.5 [get_ports S1_RREADY]
set_property src_info {type:SCOPED_XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -max 2.0 [get_ports S2_AWADDR*]
set_property src_info {type:SCOPED_XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -min 0.5 [get_ports S2_AWADDR*]
set_property src_info {type:SCOPED_XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -max 2.0 [get_ports S2_ARADDR*]
set_property src_info {type:SCOPED_XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -min 0.5 [get_ports S2_ARADDR*]
set_property src_info {type:SCOPED_XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -max 2.0 [get_ports S2_WDATA*]
set_property src_info {type:SCOPED_XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -min 0.5 [get_ports S2_WDATA*]
set_property src_info {type:SCOPED_XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -max 2.0 [get_ports S2_AWVALID]
set_property src_info {type:SCOPED_XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -min 0.5 [get_ports S2_AWVALID]
set_property src_info {type:SCOPED_XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -max 2.0 [get_ports S2_ARVALID]
set_property src_info {type:SCOPED_XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -min 0.5 [get_ports S2_ARVALID]
set_property src_info {type:SCOPED_XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -max 2.0 [get_ports S2_WVALID]
set_property src_info {type:SCOPED_XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -min 0.5 [get_ports S2_WVALID]
set_property src_info {type:SCOPED_XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -max 2.0 [get_ports S2_BREADY]
set_property src_info {type:SCOPED_XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -min 0.5 [get_ports S2_BREADY]
set_property src_info {type:SCOPED_XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -max 2.0 [get_ports S2_RREADY]
set_property src_info {type:SCOPED_XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -min 0.5 [get_ports S2_RREADY]
set_property src_info {type:SCOPED_XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -max 2.0 [get_ports S3_AWADDR*]
set_property src_info {type:SCOPED_XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -min 0.5 [get_ports S3_AWADDR*]
set_property src_info {type:SCOPED_XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -max 2.0 [get_ports S3_ARADDR*]
set_property src_info {type:SCOPED_XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -min 0.5 [get_ports S3_ARADDR*]
set_property src_info {type:SCOPED_XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -max 2.0 [get_ports S3_WDATA*]
set_property src_info {type:SCOPED_XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -min 0.5 [get_ports S3_WDATA*]
set_property src_info {type:SCOPED_XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -max 2.0 [get_ports S3_AWVALID]
set_property src_info {type:SCOPED_XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -min 0.5 [get_ports S3_AWVALID]
set_property src_info {type:SCOPED_XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -max 2.0 [get_ports S3_ARVALID]
set_property src_info {type:SCOPED_XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -min 0.5 [get_ports S3_ARVALID]
set_property src_info {type:SCOPED_XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -max 2.0 [get_ports S3_WVALID]
set_property src_info {type:SCOPED_XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -min 0.5 [get_ports S3_WVALID]
set_property src_info {type:SCOPED_XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -max 2.0 [get_ports S3_BREADY]
set_property src_info {type:SCOPED_XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -min 0.5 [get_ports S3_BREADY]
set_property src_info {type:SCOPED_XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -max 2.0 [get_ports S3_RREADY]
set_property src_info {type:SCOPED_XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ACLK -min 0.5 [get_ports S3_RREADY]
