# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Nguyen Ha Hai/axi4-system-suite/synthesis/scripts/vivado/axi4_system_sv_kv260/axi4_system_sv_kv260.srcs/sources_1/bd/design_1/ip/design_1_axi_slave_bridge_s2_0/design_1_axi_slave_bridge_s2_0.xci
# IP: The module: 'design_1_axi_slave_bridge_s2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Nguyen Ha Hai/axi4-system-suite/synthesis/scripts/vivado/axi4_system_sv_kv260/axi4_system_sv_kv260.gen/sources_1/bd/design_1/ip/design_1_axi_slave_bridge_s2_0/src/design_1_axi_master_bridge_0_0/design_1_axi_master_bridge_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_master_bridge_0_0 || ORIG_REF_NAME==design_1_axi_master_bridge_0_0} -quiet] -quiet

# IP: c:/Users/Nguyen Ha Hai/axi4-system-suite/synthesis/scripts/vivado/axi4_system_sv_kv260/axi4_system_sv_kv260.gen/sources_1/bd/design_1/ip/design_1_axi_slave_bridge_s2_0/src/design_1_axi_master_bridge_1_0/design_1_axi_master_bridge_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_master_bridge_1_0 || ORIG_REF_NAME==design_1_axi_master_bridge_1_0} -quiet] -quiet

# XDC: c:/Users/Nguyen Ha Hai/axi4-system-suite/synthesis/scripts/vivado/axi4_system_sv_kv260/axi4_system_sv_kv260.gen/sources_1/bd/design_1/ip/design_1_axi_slave_bridge_s2_0/src/design_1_axi_master_bridge_0_0/src/axi_interconnect.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_master_bridge_0_0 || ORIG_REF_NAME==design_1_axi_master_bridge_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Nguyen Ha Hai/axi4-system-suite/synthesis/scripts/vivado/axi4_system_sv_kv260/axi4_system_sv_kv260.gen/sources_1/bd/design_1/ip/design_1_axi_slave_bridge_s2_0/src/axi_interconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_slave_bridge_s2_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Nguyen Ha Hai/axi4-system-suite/synthesis/scripts/vivado/axi4_system_sv_kv260/axi4_system_sv_kv260.gen/sources_1/bd/design_1/ip/design_1_axi_slave_bridge_s2_0/src/design_1_axi_master_bridge_1_0/src/axi_interconnect.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_master_bridge_1_0 || ORIG_REF_NAME==design_1_axi_master_bridge_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# IP: C:/Users/Nguyen Ha Hai/axi4-system-suite/synthesis/scripts/vivado/axi4_system_sv_kv260/axi4_system_sv_kv260.srcs/sources_1/bd/design_1/ip/design_1_axi_slave_bridge_s2_0/design_1_axi_slave_bridge_s2_0.xci
# IP: The module: 'design_1_axi_slave_bridge_s2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Nguyen Ha Hai/axi4-system-suite/synthesis/scripts/vivado/axi4_system_sv_kv260/axi4_system_sv_kv260.gen/sources_1/bd/design_1/ip/design_1_axi_slave_bridge_s2_0/src/design_1_axi_master_bridge_0_0/design_1_axi_master_bridge_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_master_bridge_0_0 || ORIG_REF_NAME==design_1_axi_master_bridge_0_0} -quiet] -quiet

# IP: c:/Users/Nguyen Ha Hai/axi4-system-suite/synthesis/scripts/vivado/axi4_system_sv_kv260/axi4_system_sv_kv260.gen/sources_1/bd/design_1/ip/design_1_axi_slave_bridge_s2_0/src/design_1_axi_master_bridge_1_0/design_1_axi_master_bridge_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_master_bridge_1_0 || ORIG_REF_NAME==design_1_axi_master_bridge_1_0} -quiet] -quiet

# XDC: c:/Users/Nguyen Ha Hai/axi4-system-suite/synthesis/scripts/vivado/axi4_system_sv_kv260/axi4_system_sv_kv260.gen/sources_1/bd/design_1/ip/design_1_axi_slave_bridge_s2_0/src/design_1_axi_master_bridge_0_0/src/axi_interconnect.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_master_bridge_0_0 || ORIG_REF_NAME==design_1_axi_master_bridge_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Nguyen Ha Hai/axi4-system-suite/synthesis/scripts/vivado/axi4_system_sv_kv260/axi4_system_sv_kv260.gen/sources_1/bd/design_1/ip/design_1_axi_slave_bridge_s2_0/src/axi_interconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_slave_bridge_s2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Nguyen Ha Hai/axi4-system-suite/synthesis/scripts/vivado/axi4_system_sv_kv260/axi4_system_sv_kv260.gen/sources_1/bd/design_1/ip/design_1_axi_slave_bridge_s2_0/src/design_1_axi_master_bridge_1_0/src/axi_interconnect.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_master_bridge_1_0 || ORIG_REF_NAME==design_1_axi_master_bridge_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet
