create_clock -period 10.000 -name ACLK [get_ports ACLK]


set_clock_uncertainty -setup 0.5 [get_clocks ACLK]
set_clock_uncertainty -hold 0.2 [get_clocks ACLK]



set_false_path -from [get_ports ARESETN]

set_input_delay -clock ACLK -max 2.0 [get_ports M0_AWADDR*]
set_input_delay -clock ACLK -min 0.5 [get_ports M0_AWADDR*]
set_input_delay -clock ACLK -max 2.0 [get_ports M0_ARADDR*]
set_input_delay -clock ACLK -min 0.5 [get_ports M0_ARADDR*]

set_input_delay -clock ACLK -max 2.0 [get_ports M0_WDATA*]
set_input_delay -clock ACLK -min 0.5 [get_ports M0_WDATA*]

set_input_delay -clock ACLK -max 2.0 [get_ports M0_AWVALID]
set_input_delay -clock ACLK -min 0.5 [get_ports M0_AWVALID]
set_input_delay -clock ACLK -max 2.0 [get_ports M0_ARVALID]
set_input_delay -clock ACLK -min 0.5 [get_ports M0_ARVALID]
set_input_delay -clock ACLK -max 2.0 [get_ports M0_WVALID]
set_input_delay -clock ACLK -min 0.5 [get_ports M0_WVALID]
set_input_delay -clock ACLK -max 2.0 [get_ports M0_BREADY]
set_input_delay -clock ACLK -min 0.5 [get_ports M0_BREADY]
set_input_delay -clock ACLK -max 2.0 [get_ports M0_RREADY]
set_input_delay -clock ACLK -min 0.5 [get_ports M0_RREADY]

set_input_delay -clock ACLK -max 2.0 [get_ports M1_AWADDR*]
set_input_delay -clock ACLK -min 0.5 [get_ports M1_AWADDR*]
set_input_delay -clock ACLK -max 2.0 [get_ports M1_ARADDR*]
set_input_delay -clock ACLK -min 0.5 [get_ports M1_ARADDR*]
set_input_delay -clock ACLK -max 2.0 [get_ports M1_WDATA*]
set_input_delay -clock ACLK -min 0.5 [get_ports M1_WDATA*]
set_input_delay -clock ACLK -max 2.0 [get_ports M1_AWVALID]
set_input_delay -clock ACLK -min 0.5 [get_ports M1_AWVALID]
set_input_delay -clock ACLK -max 2.0 [get_ports M1_ARVALID]
set_input_delay -clock ACLK -min 0.5 [get_ports M1_ARVALID]
set_input_delay -clock ACLK -max 2.0 [get_ports M1_WVALID]
set_input_delay -clock ACLK -min 0.5 [get_ports M1_WVALID]
set_input_delay -clock ACLK -max 2.0 [get_ports M1_BREADY]
set_input_delay -clock ACLK -min 0.5 [get_ports M1_BREADY]
set_input_delay -clock ACLK -max 2.0 [get_ports M1_RREADY]
set_input_delay -clock ACLK -min 0.5 [get_ports M1_RREADY]

set_output_delay -clock ACLK -max 2.0 [get_ports S0_AWADDR*]
set_output_delay -clock ACLK -min 0.5 [get_ports S0_AWADDR*]
set_output_delay -clock ACLK -max 2.0 [get_ports S0_ARADDR*]
set_output_delay -clock ACLK -min 0.5 [get_ports S0_ARADDR*]
set_output_delay -clock ACLK -max 2.0 [get_ports S0_WDATA*]
set_output_delay -clock ACLK -min 0.5 [get_ports S0_WDATA*]
set_output_delay -clock ACLK -max 2.0 [get_ports S0_AWVALID]
set_output_delay -clock ACLK -min 0.5 [get_ports S0_AWVALID]
set_output_delay -clock ACLK -max 2.0 [get_ports S0_ARVALID]
set_output_delay -clock ACLK -min 0.5 [get_ports S0_ARVALID]
set_output_delay -clock ACLK -max 2.0 [get_ports S0_WVALID]
set_output_delay -clock ACLK -min 0.5 [get_ports S0_WVALID]
set_output_delay -clock ACLK -max 2.0 [get_ports S0_BREADY]
set_output_delay -clock ACLK -min 0.5 [get_ports S0_BREADY]
set_output_delay -clock ACLK -max 2.0 [get_ports S0_RREADY]
set_output_delay -clock ACLK -min 0.5 [get_ports S0_RREADY]

set_output_delay -clock ACLK -max 2.0 [get_ports S1_AWADDR*]
set_output_delay -clock ACLK -min 0.5 [get_ports S1_AWADDR*]
set_output_delay -clock ACLK -max 2.0 [get_ports S1_ARADDR*]
set_output_delay -clock ACLK -min 0.5 [get_ports S1_ARADDR*]
set_output_delay -clock ACLK -max 2.0 [get_ports S1_WDATA*]
set_output_delay -clock ACLK -min 0.5 [get_ports S1_WDATA*]
set_output_delay -clock ACLK -max 2.0 [get_ports S1_AWVALID]
set_output_delay -clock ACLK -min 0.5 [get_ports S1_AWVALID]
set_output_delay -clock ACLK -max 2.0 [get_ports S1_ARVALID]
set_output_delay -clock ACLK -min 0.5 [get_ports S1_ARVALID]
set_output_delay -clock ACLK -max 2.0 [get_ports S1_WVALID]
set_output_delay -clock ACLK -min 0.5 [get_ports S1_WVALID]
set_output_delay -clock ACLK -max 2.0 [get_ports S1_BREADY]
set_output_delay -clock ACLK -min 0.5 [get_ports S1_BREADY]
set_output_delay -clock ACLK -max 2.0 [get_ports S1_RREADY]
set_output_delay -clock ACLK -min 0.5 [get_ports S1_RREADY]

set_output_delay -clock ACLK -max 2.0 [get_ports S2_AWADDR*]
set_output_delay -clock ACLK -min 0.5 [get_ports S2_AWADDR*]
set_output_delay -clock ACLK -max 2.0 [get_ports S2_ARADDR*]
set_output_delay -clock ACLK -min 0.5 [get_ports S2_ARADDR*]
set_output_delay -clock ACLK -max 2.0 [get_ports S2_WDATA*]
set_output_delay -clock ACLK -min 0.5 [get_ports S2_WDATA*]
set_output_delay -clock ACLK -max 2.0 [get_ports S2_AWVALID]
set_output_delay -clock ACLK -min 0.5 [get_ports S2_AWVALID]
set_output_delay -clock ACLK -max 2.0 [get_ports S2_ARVALID]
set_output_delay -clock ACLK -min 0.5 [get_ports S2_ARVALID]
set_output_delay -clock ACLK -max 2.0 [get_ports S2_WVALID]
set_output_delay -clock ACLK -min 0.5 [get_ports S2_WVALID]
set_output_delay -clock ACLK -max 2.0 [get_ports S2_BREADY]
set_output_delay -clock ACLK -min 0.5 [get_ports S2_BREADY]
set_output_delay -clock ACLK -max 2.0 [get_ports S2_RREADY]
set_output_delay -clock ACLK -min 0.5 [get_ports S2_RREADY]

set_output_delay -clock ACLK -max 2.0 [get_ports S3_AWADDR*]
set_output_delay -clock ACLK -min 0.5 [get_ports S3_AWADDR*]
set_output_delay -clock ACLK -max 2.0 [get_ports S3_ARADDR*]
set_output_delay -clock ACLK -min 0.5 [get_ports S3_ARADDR*]
set_output_delay -clock ACLK -max 2.0 [get_ports S3_WDATA*]
set_output_delay -clock ACLK -min 0.5 [get_ports S3_WDATA*]
set_output_delay -clock ACLK -max 2.0 [get_ports S3_AWVALID]
set_output_delay -clock ACLK -min 0.5 [get_ports S3_AWVALID]
set_output_delay -clock ACLK -max 2.0 [get_ports S3_ARVALID]
set_output_delay -clock ACLK -min 0.5 [get_ports S3_ARVALID]
set_output_delay -clock ACLK -max 2.0 [get_ports S3_WVALID]
set_output_delay -clock ACLK -min 0.5 [get_ports S3_WVALID]
set_output_delay -clock ACLK -max 2.0 [get_ports S3_BREADY]
set_output_delay -clock ACLK -min 0.5 [get_ports S3_BREADY]
set_output_delay -clock ACLK -max 2.0 [get_ports S3_RREADY]
set_output_delay -clock ACLK -min 0.5 [get_ports S3_RREADY]


