set_property SRC_FILE_INFO {cfile:{C:/Users/Nguyen Ha Hai/axi4-system-suite/synthesis/constraints/axi_interconnect.xdc} rfile:../../../../../../constraints/axi_interconnect.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name ACLK [get_ports ACLK]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_clock_uncertainty -setup 0.5 [get_clocks ACLK]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_clock_uncertainty -hold 0.2 [get_clocks ACLK]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_ports ARESETN]
