library verilog;
use verilog.vl_types.all;
entity AXI_Interconnect is
    generic(
        ARBITRATION_MODE: integer := 1
    );
    port(
        ACLK            : in     vl_logic;
        ARESETN         : in     vl_logic;
        M0_AWADDR       : in     vl_logic_vector(31 downto 0);
        M0_AWLEN        : in     vl_logic_vector(7 downto 0);
        M0_AWSIZE       : in     vl_logic_vector(2 downto 0);
        M0_AWBURST      : in     vl_logic_vector(1 downto 0);
        M0_AWVALID      : in     vl_logic;
        M0_AWREADY      : out    vl_logic;
        M0_WDATA        : in     vl_logic_vector(31 downto 0);
        M0_WSTRB        : in     vl_logic_vector(3 downto 0);
        M0_WLAST        : in     vl_logic;
        M0_WVALID       : in     vl_logic;
        M0_WREADY       : out    vl_logic;
        M0_BRESP        : out    vl_logic_vector(1 downto 0);
        M0_BVALID       : out    vl_logic;
        M0_BREADY       : in     vl_logic;
        M0_ARADDR       : in     vl_logic_vector(31 downto 0);
        M0_ARLEN        : in     vl_logic_vector(7 downto 0);
        M0_ARSIZE       : in     vl_logic_vector(2 downto 0);
        M0_ARBURST      : in     vl_logic_vector(1 downto 0);
        M0_ARVALID      : in     vl_logic;
        M0_ARREADY      : out    vl_logic;
        M0_RDATA        : out    vl_logic_vector(31 downto 0);
        M0_RRESP        : out    vl_logic_vector(1 downto 0);
        M0_RLAST        : out    vl_logic;
        M0_RVALID       : out    vl_logic;
        M0_RREADY       : in     vl_logic;
        M1_AWADDR       : in     vl_logic_vector(31 downto 0);
        M1_AWLEN        : in     vl_logic_vector(7 downto 0);
        M1_AWSIZE       : in     vl_logic_vector(2 downto 0);
        M1_AWBURST      : in     vl_logic_vector(1 downto 0);
        M1_AWVALID      : in     vl_logic;
        M1_AWREADY      : out    vl_logic;
        M1_WDATA        : in     vl_logic_vector(31 downto 0);
        M1_WSTRB        : in     vl_logic_vector(3 downto 0);
        M1_WLAST        : in     vl_logic;
        M1_WVALID       : in     vl_logic;
        M1_WREADY       : out    vl_logic;
        M1_BRESP        : out    vl_logic_vector(1 downto 0);
        M1_BVALID       : out    vl_logic;
        M1_BREADY       : in     vl_logic;
        M1_ARADDR       : in     vl_logic_vector(31 downto 0);
        M1_ARLEN        : in     vl_logic_vector(7 downto 0);
        M1_ARSIZE       : in     vl_logic_vector(2 downto 0);
        M1_ARBURST      : in     vl_logic_vector(1 downto 0);
        M1_ARVALID      : in     vl_logic;
        M1_ARREADY      : out    vl_logic;
        M1_RDATA        : out    vl_logic_vector(31 downto 0);
        M1_RRESP        : out    vl_logic_vector(1 downto 0);
        M1_RLAST        : out    vl_logic;
        M1_RVALID       : out    vl_logic;
        M1_RREADY       : in     vl_logic;
        S0_AWADDR       : out    vl_logic_vector(31 downto 0);
        S0_AWLEN        : out    vl_logic_vector(7 downto 0);
        S0_AWSIZE       : out    vl_logic_vector(2 downto 0);
        S0_AWBURST      : out    vl_logic_vector(1 downto 0);
        S0_AWVALID      : out    vl_logic;
        S0_AWREADY      : in     vl_logic;
        S0_WDATA        : out    vl_logic_vector(31 downto 0);
        S0_WSTRB        : out    vl_logic_vector(3 downto 0);
        S0_WLAST        : out    vl_logic;
        S0_WVALID       : out    vl_logic;
        S0_WREADY       : in     vl_logic;
        S0_BRESP        : in     vl_logic_vector(1 downto 0);
        S0_BVALID       : in     vl_logic;
        S0_BREADY       : out    vl_logic;
        S0_ARADDR       : out    vl_logic_vector(31 downto 0);
        S0_ARLEN        : out    vl_logic_vector(7 downto 0);
        S0_ARSIZE       : out    vl_logic_vector(2 downto 0);
        S0_ARBURST      : out    vl_logic_vector(1 downto 0);
        S0_ARVALID      : out    vl_logic;
        S0_ARREADY      : in     vl_logic;
        S0_RDATA        : in     vl_logic_vector(31 downto 0);
        S0_RRESP        : in     vl_logic_vector(1 downto 0);
        S0_RLAST        : in     vl_logic;
        S0_RVALID       : in     vl_logic;
        S0_RREADY       : out    vl_logic;
        S1_AWADDR       : out    vl_logic_vector(31 downto 0);
        S1_AWLEN        : out    vl_logic_vector(7 downto 0);
        S1_AWSIZE       : out    vl_logic_vector(2 downto 0);
        S1_AWBURST      : out    vl_logic_vector(1 downto 0);
        S1_AWVALID      : out    vl_logic;
        S1_AWREADY      : in     vl_logic;
        S1_WDATA        : out    vl_logic_vector(31 downto 0);
        S1_WSTRB        : out    vl_logic_vector(3 downto 0);
        S1_WLAST        : out    vl_logic;
        S1_WVALID       : out    vl_logic;
        S1_WREADY       : in     vl_logic;
        S1_BRESP        : in     vl_logic_vector(1 downto 0);
        S1_BVALID       : in     vl_logic;
        S1_BREADY       : out    vl_logic;
        S1_ARADDR       : out    vl_logic_vector(31 downto 0);
        S1_ARLEN        : out    vl_logic_vector(7 downto 0);
        S1_ARSIZE       : out    vl_logic_vector(2 downto 0);
        S1_ARBURST      : out    vl_logic_vector(1 downto 0);
        S1_ARVALID      : out    vl_logic;
        S1_ARREADY      : in     vl_logic;
        S1_RDATA        : in     vl_logic_vector(31 downto 0);
        S1_RRESP        : in     vl_logic_vector(1 downto 0);
        S1_RLAST        : in     vl_logic;
        S1_RVALID       : in     vl_logic;
        S1_RREADY       : out    vl_logic;
        S2_AWADDR       : out    vl_logic_vector(31 downto 0);
        S2_AWLEN        : out    vl_logic_vector(7 downto 0);
        S2_AWSIZE       : out    vl_logic_vector(2 downto 0);
        S2_AWBURST      : out    vl_logic_vector(1 downto 0);
        S2_AWVALID      : out    vl_logic;
        S2_AWREADY      : in     vl_logic;
        S2_WDATA        : out    vl_logic_vector(31 downto 0);
        S2_WSTRB        : out    vl_logic_vector(3 downto 0);
        S2_WLAST        : out    vl_logic;
        S2_WVALID       : out    vl_logic;
        S2_WREADY       : in     vl_logic;
        S2_BRESP        : in     vl_logic_vector(1 downto 0);
        S2_BVALID       : in     vl_logic;
        S2_BREADY       : out    vl_logic;
        S2_ARADDR       : out    vl_logic_vector(31 downto 0);
        S2_ARLEN        : out    vl_logic_vector(7 downto 0);
        S2_ARSIZE       : out    vl_logic_vector(2 downto 0);
        S2_ARBURST      : out    vl_logic_vector(1 downto 0);
        S2_ARVALID      : out    vl_logic;
        S2_ARREADY      : in     vl_logic;
        S2_RDATA        : in     vl_logic_vector(31 downto 0);
        S2_RRESP        : in     vl_logic_vector(1 downto 0);
        S2_RLAST        : in     vl_logic;
        S2_RVALID       : in     vl_logic;
        S2_RREADY       : out    vl_logic;
        S3_AWADDR       : out    vl_logic_vector(31 downto 0);
        S3_AWLEN        : out    vl_logic_vector(7 downto 0);
        S3_AWSIZE       : out    vl_logic_vector(2 downto 0);
        S3_AWBURST      : out    vl_logic_vector(1 downto 0);
        S3_AWVALID      : out    vl_logic;
        S3_AWREADY      : in     vl_logic;
        S3_WDATA        : out    vl_logic_vector(31 downto 0);
        S3_WSTRB        : out    vl_logic_vector(3 downto 0);
        S3_WLAST        : out    vl_logic;
        S3_WVALID       : out    vl_logic;
        S3_WREADY       : in     vl_logic;
        S3_BRESP        : in     vl_logic_vector(1 downto 0);
        S3_BVALID       : in     vl_logic;
        S3_BREADY       : out    vl_logic;
        S3_ARADDR       : out    vl_logic_vector(31 downto 0);
        S3_ARLEN        : out    vl_logic_vector(7 downto 0);
        S3_ARSIZE       : out    vl_logic_vector(2 downto 0);
        S3_ARBURST      : out    vl_logic_vector(1 downto 0);
        S3_ARVALID      : out    vl_logic;
        S3_ARREADY      : in     vl_logic;
        S3_RDATA        : in     vl_logic_vector(31 downto 0);
        S3_RRESP        : in     vl_logic_vector(1 downto 0);
        S3_RLAST        : in     vl_logic;
        S3_RVALID       : in     vl_logic;
        S3_RREADY       : out    vl_logic
    );
    attribute mti_svvh_generic_type : integer;
    attribute mti_svvh_generic_type of ARBITRATION_MODE : constant is 2;
end AXI_Interconnect;
