# ==============================================================================
# Auto-Compile and Verify FRISCV AXI System
# ==============================================================================
# Auto-generated by: AXI Bridge Integration Tool
# ==============================================================================

puts "\n======================================================================"
puts "   AUTO-COMPILE AND VERIFY: FRISCV AXI SYSTEM"
puts "======================================================================\n"

# ==============================================================================
# Step 1: Setup Work Library
# ==============================================================================
puts "\[1/5\] Setting up work library..."

catch {quit -sim}
catch {vdel -all -lib work}
vlib work
vmap work work

puts "  ✅ Work library ready\n"

# ==============================================================================
# Step 2: Compile FRISCV Core
# ==============================================================================
puts "\[2/5\] Compiling FRISCV core and dependencies..."

set FRISCV_RTL "../../../src/cores/friscv/friscv/rtl"
set error_count 0

# ✅ FIX: Add include path and compile in correct order
# FRISCV uses SystemVerilog includes that need proper path setup

puts "  Setting include path: $FRISCV_RTL"

# Compile header files FIRST (required by other modules)
set header_files {
    "friscv_h.sv"
    "friscv_debug_h.sv"
    "friscv_memfy_h.sv"
    "friscv_control_h.sv"
    "friscv_checkers.sv"
}

foreach file $header_files {
    set filepath "$FRISCV_RTL/$file"
    if {[file exists $filepath]} {
        if {[catch {vlog -sv +incdir+$FRISCV_RTL -work work $filepath} result]} {
            puts "  ⚠️  Could not compile $file (may be included only)"
        } else {
            puts "  ✅ Compiled header: $file"
        }
    }
}

# Now compile all other files with include path
set friscv_files [glob -directory $FRISCV_RTL "*.sv"]

puts "  Compiling [llength $friscv_files] SystemVerilog files with +incdir..."

foreach file $friscv_files {
    # Skip headers (already compiled)
    set filename [file tail $file]
    if {[lsearch $header_files $filename] >= 0} {
        continue
    }
    
    # Compile with include directory
    if {[catch {vlog -sv +incdir+$FRISCV_RTL -work work $file} result]} {
        # Check if it's just a warning about already compiled
        if {![string match "*already compiled*" $result]} {
            puts "  ❌ ERROR compiling $filename"
            puts $result
            incr error_count
        }
    }
}

if {$error_count > 0} {
    puts "\n  ❌ $error_count compilation errors!"
    puts "  ABORTING\n"
    quit -f
}

puts "  ✅ FRISCV core compiled ([llength $friscv_files] files)\n"

# ==============================================================================
# Step 3: Compile AXI Width Adapter Bridge
# ==============================================================================
puts "\[3/5\] Compiling AXI width adapter bridge..."

if {[catch {vlog -sv -work work ../../../src/axi_bridge/rtl/axi_width_adapter_128to32.sv} result]} {
    puts "  ❌ ERROR compiling width adapter!"
    puts $result
    quit -f
}

puts "  ✅ Width adapter compiled\n"

# ==============================================================================
# Step 4: Compile Interconnect and Peripherals
# ==============================================================================
puts "\[4/5\] Compiling AXI Interconnect and peripherals..."

# Use existing compilation script
if {[file exists "compile_full_rv32i_system.tcl"]} {
    source compile_full_rv32i_system.tcl
    puts "  ✅ Interconnect and peripherals compiled\n"
} else {
    puts "  ⚠️  compile_full_rv32i_system.tcl not found"
    puts "  Compiling manually...\n"
    
    # Compile interconnect modules (simplified)
    set AXI_RTL "../../../src/axi_interconnect/Verilog/rtl"
    
    # Utils
    vlog -work work ${AXI_RTL}/utils/Raising_Edge_Det.v
    vlog -work work ${AXI_RTL}/utils/Faling_Edge_Detc.v
    
    # Buffers
    vlog -work work ${AXI_RTL}/buffers/Queue.v
    
    # Mux/Demux
    vlog -work work ${AXI_RTL}/datapath/mux/Mux_2x1.v
    vlog -work work ${AXI_RTL}/datapath/mux/Mux_4x1.v
    vlog -work work ${AXI_RTL}/datapath/mux/AW_MUX_2_1.v
    vlog -work work ${AXI_RTL}/datapath/mux/WD_MUX_2_1.v
    vlog -work work ${AXI_RTL}/datapath/mux/BReady_MUX_2_1.v
    vlog -work work ${AXI_RTL}/datapath/demux/Demux_1_2.v
    vlog -work work ${AXI_RTL}/datapath/demux/Demux_1x2.v
    vlog -work work ${AXI_RTL}/datapath/demux/Demux_1x4.v
    
    # Decoders
    vlog -work work ${AXI_RTL}/decoders/Read_Addr_Channel_Dec.v
    vlog -work work ${AXI_RTL}/decoders/Write_Addr_Channel_Dec.v
    vlog -work work ${AXI_RTL}/decoders/Write_Resp_Channel_Dec.v
    vlog -work work ${AXI_RTL}/decoders/Write_Resp_Channel_Arb.v
    
    # Handshake
    vlog -work work ${AXI_RTL}/handshake/AW_HandShake_Checker.v
    vlog -work work ${AXI_RTL}/handshake/WD_HandShake.v
    vlog -work work ${AXI_RTL}/handshake/WR_HandShake.v
    
    # Arbitration
    vlog -work work ${AXI_RTL}/arbitration/algorithms/arbiter_fixed_priority.v
    vlog -work work ${AXI_RTL}/arbitration/algorithms/arbiter_round_robin.v
    vlog -work work ${AXI_RTL}/arbitration/algorithms/arbiter_qos_based.v
    vlog -work work ${AXI_RTL}/arbitration/algorithms/read_arbiter.v
    
    # Controllers
    vlog -work work ${AXI_RTL}/channel_controllers/write/AW_Channel_Controller_Top.v
    vlog -work work ${AXI_RTL}/channel_controllers/write/WD_Channel_Controller_Top.v
    vlog -work work ${AXI_RTL}/channel_controllers/write/BR_Channel_Controller_Top.v
    vlog -work work ${AXI_RTL}/channel_controllers/read/AR_Channel_Controller_Top.v
    vlog -work work ${AXI_RTL}/channel_controllers/read/Controller.v
    
    # Core
    vlog -work work ${AXI_RTL}/core/AXI_Interconnect_Full.v
    vlog -work work ${AXI_RTL}/core/AXI_Interconnect.v
    
    # Peripherals
    vlog -work work ../../../src/peripherals/axi_lite/axi_lite_ram.v
    vlog -work work ../../../src/peripherals/axi_lite/axi_lite_gpio.v
    vlog -work work ../../../src/peripherals/axi_lite/axi_lite_uart.v
    vlog -work work ../../../src/peripherals/axi_lite/axi_lite_spi.v
    
    puts "  ✅ Interconnect compiled\n"
}

# ==============================================================================
# Step 5: Compile System and Testbench
# ==============================================================================
puts "\[5/5\] Compiling FRISCV system and testbench..."

# Compile system
if {[catch {vlog -sv -work work ../../../src/systems/friscv_axi_system.sv} result]} {
    puts "  ❌ ERROR compiling friscv_axi_system.sv!"
    puts $result
    quit -f
}
puts "  ✅ System compiled"

# Compile testbench
if {[catch {vlog -sv -work work tb_friscv_auto_verify.sv} result]} {
    puts "  ❌ ERROR compiling testbench!"
    puts $result
    quit -f
}
puts "  ✅ Testbench compiled\n"

puts "======================================================================"
puts "  ✅ COMPILATION COMPLETE - 0 ERRORS"
puts "======================================================================\n"

# ==============================================================================
# Run Verification
# ==============================================================================
puts "======================================================================"
puts "  STARTING AUTO-VERIFICATION"
puts "======================================================================\n"

if {[catch {vsim -voptargs=+acc work.tb_friscv_auto_verify} result]} {
    puts "❌ ERROR loading simulation!"
    puts $result
    quit -f
}

puts "Simulation loaded, running...\n"

# Run simulation
run -all

puts "\n======================================================================"
puts "  VERIFICATION COMPLETE"
puts "======================================================================\n"

puts "Check output above for test results"
puts "Waveform: tb_friscv_auto_verify.vcd\n"

quit -f

