-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2024.2 (win64) Build 5239630 Fri Nov 08 22:35:27 MST 2024
-- Date        : Sat Dec 20 09:47:20 2025
-- Host        : NGUYEN-HA-HAI running 64-bit major release  (build 9200)
-- Command     : write_vhdl -force -mode synth_stub {c:/Users/Nguyen Ha
--               Hai/axi4-system-suite/synthesis/scripts/vivado/axi4_system_sv_kv260/axi4_system_sv_kv260.gen/sources_1/bd/design_1/ip/design_1_axi_interconnect_0_0/design_1_axi_interconnect_0_0_stub.vhdl}
-- Design      : design_1_axi_interconnect_0_0
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xczu5ev-sfvc784-1-e
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity design_1_axi_interconnect_0_0 is
  Port ( 
    ACLK : in STD_LOGIC;
    ARESETN : in STD_LOGIC;
    M0_AWADDR : in STD_LOGIC_VECTOR ( 31 downto 0 );
    M0_AWLEN : in STD_LOGIC_VECTOR ( 7 downto 0 );
    M0_AWSIZE : in STD_LOGIC_VECTOR ( 2 downto 0 );
    M0_AWBURST : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M0_AWVALID : in STD_LOGIC;
    M0_AWREADY : out STD_LOGIC;
    M0_WDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    M0_WSTRB : in STD_LOGIC_VECTOR ( 3 downto 0 );
    M0_WLAST : in STD_LOGIC;
    M0_WVALID : in STD_LOGIC;
    M0_WREADY : out STD_LOGIC;
    M0_BRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    M0_BVALID : out STD_LOGIC;
    M0_BREADY : in STD_LOGIC;
    M0_ARADDR : in STD_LOGIC_VECTOR ( 31 downto 0 );
    M0_ARLEN : in STD_LOGIC_VECTOR ( 7 downto 0 );
    M0_ARSIZE : in STD_LOGIC_VECTOR ( 2 downto 0 );
    M0_ARBURST : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M0_ARVALID : in STD_LOGIC;
    M0_ARREADY : out STD_LOGIC;
    M0_RDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    M0_RRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    M0_RLAST : out STD_LOGIC;
    M0_RVALID : out STD_LOGIC;
    M0_RREADY : in STD_LOGIC;
    M1_AWADDR : in STD_LOGIC_VECTOR ( 31 downto 0 );
    M1_AWLEN : in STD_LOGIC_VECTOR ( 7 downto 0 );
    M1_AWSIZE : in STD_LOGIC_VECTOR ( 2 downto 0 );
    M1_AWBURST : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M1_AWVALID : in STD_LOGIC;
    M1_AWREADY : out STD_LOGIC;
    M1_WDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    M1_WSTRB : in STD_LOGIC_VECTOR ( 3 downto 0 );
    M1_WLAST : in STD_LOGIC;
    M1_WVALID : in STD_LOGIC;
    M1_WREADY : out STD_LOGIC;
    M1_BRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    M1_BVALID : out STD_LOGIC;
    M1_BREADY : in STD_LOGIC;
    M1_ARADDR : in STD_LOGIC_VECTOR ( 31 downto 0 );
    M1_ARLEN : in STD_LOGIC_VECTOR ( 7 downto 0 );
    M1_ARSIZE : in STD_LOGIC_VECTOR ( 2 downto 0 );
    M1_ARBURST : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M1_ARVALID : in STD_LOGIC;
    M1_ARREADY : out STD_LOGIC;
    M1_RDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    M1_RRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    M1_RLAST : out STD_LOGIC;
    M1_RVALID : out STD_LOGIC;
    M1_RREADY : in STD_LOGIC;
    S0_AWADDR : out STD_LOGIC_VECTOR ( 31 downto 0 );
    S0_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    S0_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    S0_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    S0_AWVALID : out STD_LOGIC;
    S0_AWREADY : in STD_LOGIC;
    S0_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    S0_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    S0_WLAST : out STD_LOGIC;
    S0_WVALID : out STD_LOGIC;
    S0_WREADY : in STD_LOGIC;
    S0_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    S0_BVALID : in STD_LOGIC;
    S0_BREADY : out STD_LOGIC;
    S0_ARADDR : out STD_LOGIC_VECTOR ( 31 downto 0 );
    S0_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    S0_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    S0_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    S0_ARVALID : out STD_LOGIC;
    S0_ARREADY : in STD_LOGIC;
    S0_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    S0_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    S0_RLAST : in STD_LOGIC;
    S0_RVALID : in STD_LOGIC;
    S0_RREADY : out STD_LOGIC;
    S1_AWADDR : out STD_LOGIC_VECTOR ( 31 downto 0 );
    S1_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    S1_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    S1_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    S1_AWVALID : out STD_LOGIC;
    S1_AWREADY : in STD_LOGIC;
    S1_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    S1_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    S1_WLAST : out STD_LOGIC;
    S1_WVALID : out STD_LOGIC;
    S1_WREADY : in STD_LOGIC;
    S1_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    S1_BVALID : in STD_LOGIC;
    S1_BREADY : out STD_LOGIC;
    S1_ARADDR : out STD_LOGIC_VECTOR ( 31 downto 0 );
    S1_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    S1_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    S1_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    S1_ARVALID : out STD_LOGIC;
    S1_ARREADY : in STD_LOGIC;
    S1_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    S1_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    S1_RLAST : in STD_LOGIC;
    S1_RVALID : in STD_LOGIC;
    S1_RREADY : out STD_LOGIC;
    S2_AWADDR : out STD_LOGIC_VECTOR ( 31 downto 0 );
    S2_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    S2_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    S2_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    S2_AWVALID : out STD_LOGIC;
    S2_AWREADY : in STD_LOGIC;
    S2_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    S2_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    S2_WLAST : out STD_LOGIC;
    S2_WVALID : out STD_LOGIC;
    S2_WREADY : in STD_LOGIC;
    S2_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    S2_BVALID : in STD_LOGIC;
    S2_BREADY : out STD_LOGIC;
    S2_ARADDR : out STD_LOGIC_VECTOR ( 31 downto 0 );
    S2_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    S2_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    S2_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    S2_ARVALID : out STD_LOGIC;
    S2_ARREADY : in STD_LOGIC;
    S2_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    S2_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    S2_RLAST : in STD_LOGIC;
    S2_RVALID : in STD_LOGIC;
    S2_RREADY : out STD_LOGIC;
    S3_AWADDR : out STD_LOGIC_VECTOR ( 31 downto 0 );
    S3_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    S3_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    S3_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    S3_AWVALID : out STD_LOGIC;
    S3_AWREADY : in STD_LOGIC;
    S3_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    S3_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    S3_WLAST : out STD_LOGIC;
    S3_WVALID : out STD_LOGIC;
    S3_WREADY : in STD_LOGIC;
    S3_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    S3_BVALID : in STD_LOGIC;
    S3_BREADY : out STD_LOGIC;
    S3_ARADDR : out STD_LOGIC_VECTOR ( 31 downto 0 );
    S3_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    S3_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    S3_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    S3_ARVALID : out STD_LOGIC;
    S3_ARREADY : in STD_LOGIC;
    S3_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    S3_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    S3_RLAST : in STD_LOGIC;
    S3_RVALID : in STD_LOGIC;
    S3_RREADY : out STD_LOGIC
  );

  attribute CHECK_LICENSE_TYPE : string;
  attribute CHECK_LICENSE_TYPE of design_1_axi_interconnect_0_0 : entity is "design_1_axi_interconnect_0_0,AXI_Interconnect,{}";
  attribute DowngradeIPIdentifiedWarnings : string;
  attribute DowngradeIPIdentifiedWarnings of design_1_axi_interconnect_0_0 : entity is "yes";
  attribute IP_DEFINITION_SOURCE : string;
  attribute IP_DEFINITION_SOURCE of design_1_axi_interconnect_0_0 : entity is "package_project";
end design_1_axi_interconnect_0_0;

architecture stub of design_1_axi_interconnect_0_0 is
  attribute syn_black_box : boolean;
  attribute black_box_pad_pin : string;
  attribute syn_black_box of stub : architecture is true;
  attribute black_box_pad_pin of stub : architecture is "ACLK,ARESETN,M0_AWADDR[31:0],M0_AWLEN[7:0],M0_AWSIZE[2:0],M0_AWBURST[1:0],M0_AWVALID,M0_AWREADY,M0_WDATA[31:0],M0_WSTRB[3:0],M0_WLAST,M0_WVALID,M0_WREADY,M0_BRESP[1:0],M0_BVALID,M0_BREADY,M0_ARADDR[31:0],M0_ARLEN[7:0],M0_ARSIZE[2:0],M0_ARBURST[1:0],M0_ARVALID,M0_ARREADY,M0_RDATA[31:0],M0_RRESP[1:0],M0_RLAST,M0_RVALID,M0_RREADY,M1_AWADDR[31:0],M1_AWLEN[7:0],M1_AWSIZE[2:0],M1_AWBURST[1:0],M1_AWVALID,M1_AWREADY,M1_WDATA[31:0],M1_WSTRB[3:0],M1_WLAST,M1_WVALID,M1_WREADY,M1_BRESP[1:0],M1_BVALID,M1_BREADY,M1_ARADDR[31:0],M1_ARLEN[7:0],M1_ARSIZE[2:0],M1_ARBURST[1:0],M1_ARVALID,M1_ARREADY,M1_RDATA[31:0],M1_RRESP[1:0],M1_RLAST,M1_RVALID,M1_RREADY,S0_AWADDR[31:0],S0_AWLEN[7:0],S0_AWSIZE[2:0],S0_AWBURST[1:0],S0_AWVALID,S0_AWREADY,S0_WDATA[31:0],S0_WSTRB[3:0],S0_WLAST,S0_WVALID,S0_WREADY,S0_BRESP[1:0],S0_BVALID,S0_BREADY,S0_ARADDR[31:0],S0_ARLEN[7:0],S0_ARSIZE[2:0],S0_ARBURST[1:0],S0_ARVALID,S0_ARREADY,S0_RDATA[31:0],S0_RRESP[1:0],S0_RLAST,S0_RVALID,S0_RREADY,S1_AWADDR[31:0],S1_AWLEN[7:0],S1_AWSIZE[2:0],S1_AWBURST[1:0],S1_AWVALID,S1_AWREADY,S1_WDATA[31:0],S1_WSTRB[3:0],S1_WLAST,S1_WVALID,S1_WREADY,S1_BRESP[1:0],S1_BVALID,S1_BREADY,S1_ARADDR[31:0],S1_ARLEN[7:0],S1_ARSIZE[2:0],S1_ARBURST[1:0],S1_ARVALID,S1_ARREADY,S1_RDATA[31:0],S1_RRESP[1:0],S1_RLAST,S1_RVALID,S1_RREADY,S2_AWADDR[31:0],S2_AWLEN[7:0],S2_AWSIZE[2:0],S2_AWBURST[1:0],S2_AWVALID,S2_AWREADY,S2_WDATA[31:0],S2_WSTRB[3:0],S2_WLAST,S2_WVALID,S2_WREADY,S2_BRESP[1:0],S2_BVALID,S2_BREADY,S2_ARADDR[31:0],S2_ARLEN[7:0],S2_ARSIZE[2:0],S2_ARBURST[1:0],S2_ARVALID,S2_ARREADY,S2_RDATA[31:0],S2_RRESP[1:0],S2_RLAST,S2_RVALID,S2_RREADY,S3_AWADDR[31:0],S3_AWLEN[7:0],S3_AWSIZE[2:0],S3_AWBURST[1:0],S3_AWVALID,S3_AWREADY,S3_WDATA[31:0],S3_WSTRB[3:0],S3_WLAST,S3_WVALID,S3_WREADY,S3_BRESP[1:0],S3_BVALID,S3_BREADY,S3_ARADDR[31:0],S3_ARLEN[7:0],S3_ARSIZE[2:0],S3_ARBURST[1:0],S3_ARVALID,S3_ARREADY,S3_RDATA[31:0],S3_RRESP[1:0],S3_RLAST,S3_RVALID,S3_RREADY";
  attribute X_INTERFACE_INFO : string;
  attribute X_INTERFACE_INFO of ACLK : signal is "xilinx.com:signal:clock:1.0 ACLK CLK";
  attribute X_INTERFACE_MODE : string;
  attribute X_INTERFACE_MODE of ACLK : signal is "slave";
  attribute X_INTERFACE_PARAMETER : string;
  attribute X_INTERFACE_PARAMETER of ACLK : signal is "XIL_INTERFACENAME ACLK, ASSOCIATED_BUSIF M0:M1:S0:S1:S2:S3, ASSOCIATED_RESET ARESETN, FREQ_HZ 99999001, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN design_1_zynq_ultra_ps_e_0_0_pl_clk0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of ARESETN : signal is "xilinx.com:signal:reset:1.0 ARESETN RST";
  attribute X_INTERFACE_MODE of ARESETN : signal is "slave";
  attribute X_INTERFACE_PARAMETER of ARESETN : signal is "XIL_INTERFACENAME ARESETN, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of M0_AWADDR : signal is "xilinx.com:interface:aximm:1.0 M0 AWADDR";
  attribute X_INTERFACE_MODE of M0_AWADDR : signal is "slave";
  attribute X_INTERFACE_PARAMETER of M0_AWADDR : signal is "XIL_INTERFACENAME M0, DATA_WIDTH 32, PROTOCOL AXI4, FREQ_HZ 99999001, ID_WIDTH 0, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 256, PHASE 0.0, CLK_DOMAIN design_1_zynq_ultra_ps_e_0_0_pl_clk0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of M0_AWLEN : signal is "xilinx.com:interface:aximm:1.0 M0 AWLEN";
  attribute X_INTERFACE_INFO of M0_AWSIZE : signal is "xilinx.com:interface:aximm:1.0 M0 AWSIZE";
  attribute X_INTERFACE_INFO of M0_AWBURST : signal is "xilinx.com:interface:aximm:1.0 M0 AWBURST";
  attribute X_INTERFACE_INFO of M0_AWVALID : signal is "xilinx.com:interface:aximm:1.0 M0 AWVALID";
  attribute X_INTERFACE_INFO of M0_AWREADY : signal is "xilinx.com:interface:aximm:1.0 M0 AWREADY";
  attribute X_INTERFACE_INFO of M0_WDATA : signal is "xilinx.com:interface:aximm:1.0 M0 WDATA";
  attribute X_INTERFACE_INFO of M0_WSTRB : signal is "xilinx.com:interface:aximm:1.0 M0 WSTRB";
  attribute X_INTERFACE_INFO of M0_WLAST : signal is "xilinx.com:interface:aximm:1.0 M0 WLAST";
  attribute X_INTERFACE_INFO of M0_WVALID : signal is "xilinx.com:interface:aximm:1.0 M0 WVALID";
  attribute X_INTERFACE_INFO of M0_WREADY : signal is "xilinx.com:interface:aximm:1.0 M0 WREADY";
  attribute X_INTERFACE_INFO of M0_BRESP : signal is "xilinx.com:interface:aximm:1.0 M0 BRESP";
  attribute X_INTERFACE_INFO of M0_BVALID : signal is "xilinx.com:interface:aximm:1.0 M0 BVALID";
  attribute X_INTERFACE_INFO of M0_BREADY : signal is "xilinx.com:interface:aximm:1.0 M0 BREADY";
  attribute X_INTERFACE_INFO of M0_ARADDR : signal is "xilinx.com:interface:aximm:1.0 M0 ARADDR";
  attribute X_INTERFACE_INFO of M0_ARLEN : signal is "xilinx.com:interface:aximm:1.0 M0 ARLEN";
  attribute X_INTERFACE_INFO of M0_ARSIZE : signal is "xilinx.com:interface:aximm:1.0 M0 ARSIZE";
  attribute X_INTERFACE_INFO of M0_ARBURST : signal is "xilinx.com:interface:aximm:1.0 M0 ARBURST";
  attribute X_INTERFACE_INFO of M0_ARVALID : signal is "xilinx.com:interface:aximm:1.0 M0 ARVALID";
  attribute X_INTERFACE_INFO of M0_ARREADY : signal is "xilinx.com:interface:aximm:1.0 M0 ARREADY";
  attribute X_INTERFACE_INFO of M0_RDATA : signal is "xilinx.com:interface:aximm:1.0 M0 RDATA";
  attribute X_INTERFACE_INFO of M0_RRESP : signal is "xilinx.com:interface:aximm:1.0 M0 RRESP";
  attribute X_INTERFACE_INFO of M0_RLAST : signal is "xilinx.com:interface:aximm:1.0 M0 RLAST";
  attribute X_INTERFACE_INFO of M0_RVALID : signal is "xilinx.com:interface:aximm:1.0 M0 RVALID";
  attribute X_INTERFACE_INFO of M0_RREADY : signal is "xilinx.com:interface:aximm:1.0 M0 RREADY";
  attribute X_INTERFACE_INFO of M1_AWADDR : signal is "xilinx.com:interface:aximm:1.0 M1 AWADDR";
  attribute X_INTERFACE_MODE of M1_AWADDR : signal is "slave";
  attribute X_INTERFACE_PARAMETER of M1_AWADDR : signal is "XIL_INTERFACENAME M1, DATA_WIDTH 32, PROTOCOL AXI4, FREQ_HZ 99999001, ID_WIDTH 0, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 256, PHASE 0.0, CLK_DOMAIN design_1_zynq_ultra_ps_e_0_0_pl_clk0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of M1_AWLEN : signal is "xilinx.com:interface:aximm:1.0 M1 AWLEN";
  attribute X_INTERFACE_INFO of M1_AWSIZE : signal is "xilinx.com:interface:aximm:1.0 M1 AWSIZE";
  attribute X_INTERFACE_INFO of M1_AWBURST : signal is "xilinx.com:interface:aximm:1.0 M1 AWBURST";
  attribute X_INTERFACE_INFO of M1_AWVALID : signal is "xilinx.com:interface:aximm:1.0 M1 AWVALID";
  attribute X_INTERFACE_INFO of M1_AWREADY : signal is "xilinx.com:interface:aximm:1.0 M1 AWREADY";
  attribute X_INTERFACE_INFO of M1_WDATA : signal is "xilinx.com:interface:aximm:1.0 M1 WDATA";
  attribute X_INTERFACE_INFO of M1_WSTRB : signal is "xilinx.com:interface:aximm:1.0 M1 WSTRB";
  attribute X_INTERFACE_INFO of M1_WLAST : signal is "xilinx.com:interface:aximm:1.0 M1 WLAST";
  attribute X_INTERFACE_INFO of M1_WVALID : signal is "xilinx.com:interface:aximm:1.0 M1 WVALID";
  attribute X_INTERFACE_INFO of M1_WREADY : signal is "xilinx.com:interface:aximm:1.0 M1 WREADY";
  attribute X_INTERFACE_INFO of M1_BRESP : signal is "xilinx.com:interface:aximm:1.0 M1 BRESP";
  attribute X_INTERFACE_INFO of M1_BVALID : signal is "xilinx.com:interface:aximm:1.0 M1 BVALID";
  attribute X_INTERFACE_INFO of M1_BREADY : signal is "xilinx.com:interface:aximm:1.0 M1 BREADY";
  attribute X_INTERFACE_INFO of M1_ARADDR : signal is "xilinx.com:interface:aximm:1.0 M1 ARADDR";
  attribute X_INTERFACE_INFO of M1_ARLEN : signal is "xilinx.com:interface:aximm:1.0 M1 ARLEN";
  attribute X_INTERFACE_INFO of M1_ARSIZE : signal is "xilinx.com:interface:aximm:1.0 M1 ARSIZE";
  attribute X_INTERFACE_INFO of M1_ARBURST : signal is "xilinx.com:interface:aximm:1.0 M1 ARBURST";
  attribute X_INTERFACE_INFO of M1_ARVALID : signal is "xilinx.com:interface:aximm:1.0 M1 ARVALID";
  attribute X_INTERFACE_INFO of M1_ARREADY : signal is "xilinx.com:interface:aximm:1.0 M1 ARREADY";
  attribute X_INTERFACE_INFO of M1_RDATA : signal is "xilinx.com:interface:aximm:1.0 M1 RDATA";
  attribute X_INTERFACE_INFO of M1_RRESP : signal is "xilinx.com:interface:aximm:1.0 M1 RRESP";
  attribute X_INTERFACE_INFO of M1_RLAST : signal is "xilinx.com:interface:aximm:1.0 M1 RLAST";
  attribute X_INTERFACE_INFO of M1_RVALID : signal is "xilinx.com:interface:aximm:1.0 M1 RVALID";
  attribute X_INTERFACE_INFO of M1_RREADY : signal is "xilinx.com:interface:aximm:1.0 M1 RREADY";
  attribute X_INTERFACE_INFO of S0_AWADDR : signal is "xilinx.com:interface:aximm:1.0 S0 AWADDR";
  attribute X_INTERFACE_MODE of S0_AWADDR : signal is "master";
  attribute X_INTERFACE_PARAMETER of S0_AWADDR : signal is "XIL_INTERFACENAME S0, DATA_WIDTH 32, PROTOCOL AXI4, FREQ_HZ 99999001, ID_WIDTH 0, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 256, PHASE 0.0, CLK_DOMAIN design_1_zynq_ultra_ps_e_0_0_pl_clk0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of S0_AWLEN : signal is "xilinx.com:interface:aximm:1.0 S0 AWLEN";
  attribute X_INTERFACE_INFO of S0_AWSIZE : signal is "xilinx.com:interface:aximm:1.0 S0 AWSIZE";
  attribute X_INTERFACE_INFO of S0_AWBURST : signal is "xilinx.com:interface:aximm:1.0 S0 AWBURST";
  attribute X_INTERFACE_INFO of S0_AWVALID : signal is "xilinx.com:interface:aximm:1.0 S0 AWVALID";
  attribute X_INTERFACE_INFO of S0_AWREADY : signal is "xilinx.com:interface:aximm:1.0 S0 AWREADY";
  attribute X_INTERFACE_INFO of S0_WDATA : signal is "xilinx.com:interface:aximm:1.0 S0 WDATA";
  attribute X_INTERFACE_INFO of S0_WSTRB : signal is "xilinx.com:interface:aximm:1.0 S0 WSTRB";
  attribute X_INTERFACE_INFO of S0_WLAST : signal is "xilinx.com:interface:aximm:1.0 S0 WLAST";
  attribute X_INTERFACE_INFO of S0_WVALID : signal is "xilinx.com:interface:aximm:1.0 S0 WVALID";
  attribute X_INTERFACE_INFO of S0_WREADY : signal is "xilinx.com:interface:aximm:1.0 S0 WREADY";
  attribute X_INTERFACE_INFO of S0_BRESP : signal is "xilinx.com:interface:aximm:1.0 S0 BRESP";
  attribute X_INTERFACE_INFO of S0_BVALID : signal is "xilinx.com:interface:aximm:1.0 S0 BVALID";
  attribute X_INTERFACE_INFO of S0_BREADY : signal is "xilinx.com:interface:aximm:1.0 S0 BREADY";
  attribute X_INTERFACE_INFO of S0_ARADDR : signal is "xilinx.com:interface:aximm:1.0 S0 ARADDR";
  attribute X_INTERFACE_INFO of S0_ARLEN : signal is "xilinx.com:interface:aximm:1.0 S0 ARLEN";
  attribute X_INTERFACE_INFO of S0_ARSIZE : signal is "xilinx.com:interface:aximm:1.0 S0 ARSIZE";
  attribute X_INTERFACE_INFO of S0_ARBURST : signal is "xilinx.com:interface:aximm:1.0 S0 ARBURST";
  attribute X_INTERFACE_INFO of S0_ARVALID : signal is "xilinx.com:interface:aximm:1.0 S0 ARVALID";
  attribute X_INTERFACE_INFO of S0_ARREADY : signal is "xilinx.com:interface:aximm:1.0 S0 ARREADY";
  attribute X_INTERFACE_INFO of S0_RDATA : signal is "xilinx.com:interface:aximm:1.0 S0 RDATA";
  attribute X_INTERFACE_INFO of S0_RRESP : signal is "xilinx.com:interface:aximm:1.0 S0 RRESP";
  attribute X_INTERFACE_INFO of S0_RLAST : signal is "xilinx.com:interface:aximm:1.0 S0 RLAST";
  attribute X_INTERFACE_INFO of S0_RVALID : signal is "xilinx.com:interface:aximm:1.0 S0 RVALID";
  attribute X_INTERFACE_INFO of S0_RREADY : signal is "xilinx.com:interface:aximm:1.0 S0 RREADY";
  attribute X_INTERFACE_INFO of S1_AWADDR : signal is "xilinx.com:interface:aximm:1.0 S1 AWADDR";
  attribute X_INTERFACE_MODE of S1_AWADDR : signal is "master";
  attribute X_INTERFACE_PARAMETER of S1_AWADDR : signal is "XIL_INTERFACENAME S1, DATA_WIDTH 32, PROTOCOL AXI4, FREQ_HZ 99999001, ID_WIDTH 0, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 256, PHASE 0.0, CLK_DOMAIN design_1_zynq_ultra_ps_e_0_0_pl_clk0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of S1_AWLEN : signal is "xilinx.com:interface:aximm:1.0 S1 AWLEN";
  attribute X_INTERFACE_INFO of S1_AWSIZE : signal is "xilinx.com:interface:aximm:1.0 S1 AWSIZE";
  attribute X_INTERFACE_INFO of S1_AWBURST : signal is "xilinx.com:interface:aximm:1.0 S1 AWBURST";
  attribute X_INTERFACE_INFO of S1_AWVALID : signal is "xilinx.com:interface:aximm:1.0 S1 AWVALID";
  attribute X_INTERFACE_INFO of S1_AWREADY : signal is "xilinx.com:interface:aximm:1.0 S1 AWREADY";
  attribute X_INTERFACE_INFO of S1_WDATA : signal is "xilinx.com:interface:aximm:1.0 S1 WDATA";
  attribute X_INTERFACE_INFO of S1_WSTRB : signal is "xilinx.com:interface:aximm:1.0 S1 WSTRB";
  attribute X_INTERFACE_INFO of S1_WLAST : signal is "xilinx.com:interface:aximm:1.0 S1 WLAST";
  attribute X_INTERFACE_INFO of S1_WVALID : signal is "xilinx.com:interface:aximm:1.0 S1 WVALID";
  attribute X_INTERFACE_INFO of S1_WREADY : signal is "xilinx.com:interface:aximm:1.0 S1 WREADY";
  attribute X_INTERFACE_INFO of S1_BRESP : signal is "xilinx.com:interface:aximm:1.0 S1 BRESP";
  attribute X_INTERFACE_INFO of S1_BVALID : signal is "xilinx.com:interface:aximm:1.0 S1 BVALID";
  attribute X_INTERFACE_INFO of S1_BREADY : signal is "xilinx.com:interface:aximm:1.0 S1 BREADY";
  attribute X_INTERFACE_INFO of S1_ARADDR : signal is "xilinx.com:interface:aximm:1.0 S1 ARADDR";
  attribute X_INTERFACE_INFO of S1_ARLEN : signal is "xilinx.com:interface:aximm:1.0 S1 ARLEN";
  attribute X_INTERFACE_INFO of S1_ARSIZE : signal is "xilinx.com:interface:aximm:1.0 S1 ARSIZE";
  attribute X_INTERFACE_INFO of S1_ARBURST : signal is "xilinx.com:interface:aximm:1.0 S1 ARBURST";
  attribute X_INTERFACE_INFO of S1_ARVALID : signal is "xilinx.com:interface:aximm:1.0 S1 ARVALID";
  attribute X_INTERFACE_INFO of S1_ARREADY : signal is "xilinx.com:interface:aximm:1.0 S1 ARREADY";
  attribute X_INTERFACE_INFO of S1_RDATA : signal is "xilinx.com:interface:aximm:1.0 S1 RDATA";
  attribute X_INTERFACE_INFO of S1_RRESP : signal is "xilinx.com:interface:aximm:1.0 S1 RRESP";
  attribute X_INTERFACE_INFO of S1_RLAST : signal is "xilinx.com:interface:aximm:1.0 S1 RLAST";
  attribute X_INTERFACE_INFO of S1_RVALID : signal is "xilinx.com:interface:aximm:1.0 S1 RVALID";
  attribute X_INTERFACE_INFO of S1_RREADY : signal is "xilinx.com:interface:aximm:1.0 S1 RREADY";
  attribute X_INTERFACE_INFO of S2_AWADDR : signal is "xilinx.com:interface:aximm:1.0 S2 AWADDR";
  attribute X_INTERFACE_MODE of S2_AWADDR : signal is "master";
  attribute X_INTERFACE_PARAMETER of S2_AWADDR : signal is "XIL_INTERFACENAME S2, DATA_WIDTH 32, PROTOCOL AXI4, FREQ_HZ 99999001, ID_WIDTH 0, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 256, PHASE 0.0, CLK_DOMAIN design_1_zynq_ultra_ps_e_0_0_pl_clk0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of S2_AWLEN : signal is "xilinx.com:interface:aximm:1.0 S2 AWLEN";
  attribute X_INTERFACE_INFO of S2_AWSIZE : signal is "xilinx.com:interface:aximm:1.0 S2 AWSIZE";
  attribute X_INTERFACE_INFO of S2_AWBURST : signal is "xilinx.com:interface:aximm:1.0 S2 AWBURST";
  attribute X_INTERFACE_INFO of S2_AWVALID : signal is "xilinx.com:interface:aximm:1.0 S2 AWVALID";
  attribute X_INTERFACE_INFO of S2_AWREADY : signal is "xilinx.com:interface:aximm:1.0 S2 AWREADY";
  attribute X_INTERFACE_INFO of S2_WDATA : signal is "xilinx.com:interface:aximm:1.0 S2 WDATA";
  attribute X_INTERFACE_INFO of S2_WSTRB : signal is "xilinx.com:interface:aximm:1.0 S2 WSTRB";
  attribute X_INTERFACE_INFO of S2_WLAST : signal is "xilinx.com:interface:aximm:1.0 S2 WLAST";
  attribute X_INTERFACE_INFO of S2_WVALID : signal is "xilinx.com:interface:aximm:1.0 S2 WVALID";
  attribute X_INTERFACE_INFO of S2_WREADY : signal is "xilinx.com:interface:aximm:1.0 S2 WREADY";
  attribute X_INTERFACE_INFO of S2_BRESP : signal is "xilinx.com:interface:aximm:1.0 S2 BRESP";
  attribute X_INTERFACE_INFO of S2_BVALID : signal is "xilinx.com:interface:aximm:1.0 S2 BVALID";
  attribute X_INTERFACE_INFO of S2_BREADY : signal is "xilinx.com:interface:aximm:1.0 S2 BREADY";
  attribute X_INTERFACE_INFO of S2_ARADDR : signal is "xilinx.com:interface:aximm:1.0 S2 ARADDR";
  attribute X_INTERFACE_INFO of S2_ARLEN : signal is "xilinx.com:interface:aximm:1.0 S2 ARLEN";
  attribute X_INTERFACE_INFO of S2_ARSIZE : signal is "xilinx.com:interface:aximm:1.0 S2 ARSIZE";
  attribute X_INTERFACE_INFO of S2_ARBURST : signal is "xilinx.com:interface:aximm:1.0 S2 ARBURST";
  attribute X_INTERFACE_INFO of S2_ARVALID : signal is "xilinx.com:interface:aximm:1.0 S2 ARVALID";
  attribute X_INTERFACE_INFO of S2_ARREADY : signal is "xilinx.com:interface:aximm:1.0 S2 ARREADY";
  attribute X_INTERFACE_INFO of S2_RDATA : signal is "xilinx.com:interface:aximm:1.0 S2 RDATA";
  attribute X_INTERFACE_INFO of S2_RRESP : signal is "xilinx.com:interface:aximm:1.0 S2 RRESP";
  attribute X_INTERFACE_INFO of S2_RLAST : signal is "xilinx.com:interface:aximm:1.0 S2 RLAST";
  attribute X_INTERFACE_INFO of S2_RVALID : signal is "xilinx.com:interface:aximm:1.0 S2 RVALID";
  attribute X_INTERFACE_INFO of S2_RREADY : signal is "xilinx.com:interface:aximm:1.0 S2 RREADY";
  attribute X_INTERFACE_INFO of S3_AWADDR : signal is "xilinx.com:interface:aximm:1.0 S3 AWADDR";
  attribute X_INTERFACE_MODE of S3_AWADDR : signal is "master";
  attribute X_INTERFACE_PARAMETER of S3_AWADDR : signal is "XIL_INTERFACENAME S3, DATA_WIDTH 32, PROTOCOL AXI4, FREQ_HZ 99999001, ID_WIDTH 0, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 256, PHASE 0.0, CLK_DOMAIN design_1_zynq_ultra_ps_e_0_0_pl_clk0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of S3_AWLEN : signal is "xilinx.com:interface:aximm:1.0 S3 AWLEN";
  attribute X_INTERFACE_INFO of S3_AWSIZE : signal is "xilinx.com:interface:aximm:1.0 S3 AWSIZE";
  attribute X_INTERFACE_INFO of S3_AWBURST : signal is "xilinx.com:interface:aximm:1.0 S3 AWBURST";
  attribute X_INTERFACE_INFO of S3_AWVALID : signal is "xilinx.com:interface:aximm:1.0 S3 AWVALID";
  attribute X_INTERFACE_INFO of S3_AWREADY : signal is "xilinx.com:interface:aximm:1.0 S3 AWREADY";
  attribute X_INTERFACE_INFO of S3_WDATA : signal is "xilinx.com:interface:aximm:1.0 S3 WDATA";
  attribute X_INTERFACE_INFO of S3_WSTRB : signal is "xilinx.com:interface:aximm:1.0 S3 WSTRB";
  attribute X_INTERFACE_INFO of S3_WLAST : signal is "xilinx.com:interface:aximm:1.0 S3 WLAST";
  attribute X_INTERFACE_INFO of S3_WVALID : signal is "xilinx.com:interface:aximm:1.0 S3 WVALID";
  attribute X_INTERFACE_INFO of S3_WREADY : signal is "xilinx.com:interface:aximm:1.0 S3 WREADY";
  attribute X_INTERFACE_INFO of S3_BRESP : signal is "xilinx.com:interface:aximm:1.0 S3 BRESP";
  attribute X_INTERFACE_INFO of S3_BVALID : signal is "xilinx.com:interface:aximm:1.0 S3 BVALID";
  attribute X_INTERFACE_INFO of S3_BREADY : signal is "xilinx.com:interface:aximm:1.0 S3 BREADY";
  attribute X_INTERFACE_INFO of S3_ARADDR : signal is "xilinx.com:interface:aximm:1.0 S3 ARADDR";
  attribute X_INTERFACE_INFO of S3_ARLEN : signal is "xilinx.com:interface:aximm:1.0 S3 ARLEN";
  attribute X_INTERFACE_INFO of S3_ARSIZE : signal is "xilinx.com:interface:aximm:1.0 S3 ARSIZE";
  attribute X_INTERFACE_INFO of S3_ARBURST : signal is "xilinx.com:interface:aximm:1.0 S3 ARBURST";
  attribute X_INTERFACE_INFO of S3_ARVALID : signal is "xilinx.com:interface:aximm:1.0 S3 ARVALID";
  attribute X_INTERFACE_INFO of S3_ARREADY : signal is "xilinx.com:interface:aximm:1.0 S3 ARREADY";
  attribute X_INTERFACE_INFO of S3_RDATA : signal is "xilinx.com:interface:aximm:1.0 S3 RDATA";
  attribute X_INTERFACE_INFO of S3_RRESP : signal is "xilinx.com:interface:aximm:1.0 S3 RRESP";
  attribute X_INTERFACE_INFO of S3_RLAST : signal is "xilinx.com:interface:aximm:1.0 S3 RLAST";
  attribute X_INTERFACE_INFO of S3_RVALID : signal is "xilinx.com:interface:aximm:1.0 S3 RVALID";
  attribute X_INTERFACE_INFO of S3_RREADY : signal is "xilinx.com:interface:aximm:1.0 S3 RREADY";
  attribute X_CORE_INFO : string;
  attribute X_CORE_INFO of stub : architecture is "AXI_Interconnect,Vivado 2024.2";
begin
end;
