// ==============================================================================
// Dual AXI Shell
// ==============================================================================
// Khung nối 2 AXI masters (đã qua AXI_Bridge) vào AXI_Interconnect (2M x 4S).
// Chỉ cần gắn tín hiệu master hiện có (M0, M1) và gắn 4 slave (S0-S3).
// Mặc định giữ toàn bộ kênh AXI4 đầy đủ; nếu dùng AXI4-Lite, set:
//   - AWLEN/ARLEN = 0, AWSIZE/ARSIZE = 3'b010, AWBURST/ARBURST = 2'b01
//   - WLAST/RLAST = 1
// ==============================================================================

`timescale 1ns/1ps

`include "../axi_interconnect/rtl/core/AXI_Interconnect.v"

module dual_axi_shell #(
    parameter ADDR_WIDTH = 32,
    parameter DATA_WIDTH = 32
)(
    input  wire                          ACLK,
    input  wire                          ARESETN,

    // --------------------------------------------------------------------------
    // Master 0 (từ AXI_Bridge / core 0)
    // --------------------------------------------------------------------------
    input  wire [ADDR_WIDTH-1:0]         M0_AWADDR,
    input  wire [7:0]                    M0_AWLEN,
    input  wire [2:0]                    M0_AWSIZE,
    input  wire [1:0]                    M0_AWBURST,
    input  wire                          M0_AWVALID,
    output wire                          M0_AWREADY,
    input  wire [DATA_WIDTH-1:0]         M0_WDATA,
    input  wire [DATA_WIDTH/8-1:0]       M0_WSTRB,
    input  wire                          M0_WLAST,
    input  wire                          M0_WVALID,
    output wire                          M0_WREADY,
    output wire [1:0]                    M0_BRESP,
    output wire                          M0_BVALID,
    input  wire                          M0_BREADY,
    input  wire [ADDR_WIDTH-1:0]         M0_ARADDR,
    input  wire [7:0]                    M0_ARLEN,
    input  wire [2:0]                    M0_ARSIZE,
    input  wire [1:0]                    M0_ARBURST,
    input  wire                          M0_ARVALID,
    output wire                          M0_ARREADY,
    output wire [DATA_WIDTH-1:0]         M0_RDATA,
    output wire [1:0]                    M0_RRESP,
    output wire                          M0_RLAST,
    output wire                          M0_RVALID,
    input  wire                          M0_RREADY,

    // --------------------------------------------------------------------------
    // Master 1 (từ AXI_Bridge / core 1)
    // --------------------------------------------------------------------------
    input  wire [ADDR_WIDTH-1:0]         M1_AWADDR,
    input  wire [7:0]                    M1_AWLEN,
    input  wire [2:0]                    M1_AWSIZE,
    input  wire [1:0]                    M1_AWBURST,
    input  wire                          M1_AWVALID,
    output wire                          M1_AWREADY,
    input  wire [DATA_WIDTH-1:0]         M1_WDATA,
    input  wire [DATA_WIDTH/8-1:0]       M1_WSTRB,
    input  wire                          M1_WLAST,
    input  wire                          M1_WVALID,
    output wire                          M1_WREADY,
    output wire [1:0]                    M1_BRESP,
    output wire                          M1_BVALID,
    input  wire                          M1_BREADY,
    input  wire [ADDR_WIDTH-1:0]         M1_ARADDR,
    input  wire [7:0]                    M1_ARLEN,
    input  wire [2:0]                    M1_ARSIZE,
    input  wire [1:0]                    M1_ARBURST,
    input  wire                          M1_ARVALID,
    output wire                          M1_ARREADY,
    output wire [DATA_WIDTH-1:0]         M1_RDATA,
    output wire [1:0]                    M1_RRESP,
    output wire                          M1_RLAST,
    output wire                          M1_RVALID,
    input  wire                          M1_RREADY,

    // --------------------------------------------------------------------------
    // Slave 0 (ví dụ RAM)
    // --------------------------------------------------------------------------
    output wire [ADDR_WIDTH-1:0]         S0_AWADDR,
    output wire [7:0]                    S0_AWLEN,
    output wire [2:0]                    S0_AWSIZE,
    output wire [1:0]                    S0_AWBURST,
    output wire                          S0_AWVALID,
    input  wire                          S0_AWREADY,
    output wire [DATA_WIDTH-1:0]         S0_WDATA,
    output wire [DATA_WIDTH/8-1:0]       S0_WSTRB,
    output wire                          S0_WLAST,
    output wire                          S0_WVALID,
    input  wire                          S0_WREADY,
    input  wire [1:0]                    S0_BRESP,
    input  wire                          S0_BVALID,
    output wire                          S0_BREADY,
    output wire [ADDR_WIDTH-1:0]         S0_ARADDR,
    output wire [7:0]                    S0_ARLEN,
    output wire [2:0]                    S0_ARSIZE,
    output wire [1:0]                    S0_ARBURST,
    output wire                          S0_ARVALID,
    input  wire                          S0_ARREADY,
    input  wire [DATA_WIDTH-1:0]         S0_RDATA,
    input  wire [1:0]                    S0_RRESP,
    input  wire                          S0_RLAST,
    input  wire                          S0_RVALID,
    output wire                          S0_RREADY,

    // --------------------------------------------------------------------------
    // Slave 1 (ví dụ GPIO)
    // --------------------------------------------------------------------------
    output wire [ADDR_WIDTH-1:0]         S1_AWADDR,
    output wire [7:0]                    S1_AWLEN,
    output wire [2:0]                    S1_AWSIZE,
    output wire [1:0]                    S1_AWBURST,
    output wire                          S1_AWVALID,
    input  wire                          S1_AWREADY,
    output wire [DATA_WIDTH-1:0]         S1_WDATA,
    output wire [DATA_WIDTH/8-1:0]       S1_WSTRB,
    output wire                          S1_WLAST,
    output wire                          S1_WVALID,
    input  wire                          S1_WREADY,
    input  wire [1:0]                    S1_BRESP,
    input  wire                          S1_BVALID,
    output wire                          S1_BREADY,
    output wire [ADDR_WIDTH-1:0]         S1_ARADDR,
    output wire [7:0]                    S1_ARLEN,
    output wire [2:0]                    S1_ARSIZE,
    output wire [1:0]                    S1_ARBURST,
    output wire                          S1_ARVALID,
    input  wire                          S1_ARREADY,
    input  wire [DATA_WIDTH-1:0]         S1_RDATA,
    input  wire [1:0]                    S1_RRESP,
    input  wire                          S1_RLAST,
    input  wire                          S1_RVALID,
    output wire                          S1_RREADY,

    // --------------------------------------------------------------------------
    // Slave 2 (ví dụ UART)
    // --------------------------------------------------------------------------
    output wire [ADDR_WIDTH-1:0]         S2_AWADDR,
    output wire [7:0]                    S2_AWLEN,
    output wire [2:0]                    S2_AWSIZE,
    output wire [1:0]                    S2_AWBURST,
    output wire                          S2_AWVALID,
    input  wire                          S2_AWREADY,
    output wire [DATA_WIDTH-1:0]         S2_WDATA,
    output wire [DATA_WIDTH/8-1:0]       S2_WSTRB,
    output wire                          S2_WLAST,
    output wire                          S2_WVALID,
    input  wire                          S2_WREADY,
    input  wire [1:0]                    S2_BRESP,
    input  wire                          S2_BVALID,
    output wire                          S2_BREADY,
    output wire [ADDR_WIDTH-1:0]         S2_ARADDR,
    output wire [7:0]                    S2_ARLEN,
    output wire [2:0]                    S2_ARSIZE,
    output wire [1:0]                    S2_ARBURST,
    output wire                          S2_ARVALID,
    input  wire                          S2_ARREADY,
    input  wire [DATA_WIDTH-1:0]         S2_RDATA,
    input  wire [1:0]                    S2_RRESP,
    input  wire                          S2_RLAST,
    input  wire                          S2_RVALID,
    output wire                          S2_RREADY,

    // --------------------------------------------------------------------------
    // Slave 3 (ví dụ SPI)
    // --------------------------------------------------------------------------
    output wire [ADDR_WIDTH-1:0]         S3_AWADDR,
    output wire [7:0]                    S3_AWLEN,
    output wire [2:0]                    S3_AWSIZE,
    output wire [1:0]                    S3_AWBURST,
    output wire                          S3_AWVALID,
    input  wire                          S3_AWREADY,
    output wire [DATA_WIDTH-1:0]         S3_WDATA,
    output wire [DATA_WIDTH/8-1:0]       S3_WSTRB,
    output wire                          S3_WLAST,
    output wire                          S3_WVALID,
    input  wire                          S3_WREADY,
    input  wire [1:0]                    S3_BRESP,
    input  wire                          S3_BVALID,
    output wire                          S3_BREADY,
    output wire [ADDR_WIDTH-1:0]         S3_ARADDR,
    output wire [7:0]                    S3_ARLEN,
    output wire [2:0]                    S3_ARSIZE,
    output wire [1:0]                    S3_ARBURST,
    output wire                          S3_ARVALID,
    input  wire                          S3_ARREADY,
    input  wire [DATA_WIDTH-1:0]         S3_RDATA,
    input  wire [1:0]                    S3_RRESP,
    input  wire                          S3_RLAST,
    input  wire                          S3_RVALID,
    output wire                          S3_RREADY
);

// ==============================================================================
// AXI Interconnect 2M x 4S
// ==============================================================================
AXI_Interconnect #(
    .ARBITRATION_MODE(1) // Round-Robin
) u_interconnect (
    .ACLK(ACLK),
    .ARESETN(ARESETN),

    // Master 0
    .M0_AWADDR (M0_AWADDR),
    .M0_AWLEN  (M0_AWLEN),
    .M0_AWSIZE (M0_AWSIZE),
    .M0_AWBURST(M0_AWBURST),
    .M0_AWVALID(M0_AWVALID),
    .M0_AWREADY(M0_AWREADY),
    .M0_WDATA  (M0_WDATA),
    .M0_WSTRB  (M0_WSTRB),
    .M0_WLAST  (M0_WLAST),
    .M0_WVALID (M0_WVALID),
    .M0_WREADY (M0_WREADY),
    .M0_BRESP  (M0_BRESP),
    .M0_BVALID (M0_BVALID),
    .M0_BREADY (M0_BREADY),
    .M0_ARADDR (M0_ARADDR),
    .M0_ARLEN  (M0_ARLEN),
    .M0_ARSIZE (M0_ARSIZE),
    .M0_ARBURST(M0_ARBURST),
    .M0_ARVALID(M0_ARVALID),
    .M0_ARREADY(M0_ARREADY),
    .M0_RDATA  (M0_RDATA),
    .M0_RRESP  (M0_RRESP),
    .M0_RLAST  (M0_RLAST),
    .M0_RVALID (M0_RVALID),
    .M0_RREADY (M0_RREADY),

    // Master 1
    .M1_AWADDR (M1_AWADDR),
    .M1_AWLEN  (M1_AWLEN),
    .M1_AWSIZE (M1_AWSIZE),
    .M1_AWBURST(M1_AWBURST),
    .M1_AWVALID(M1_AWVALID),
    .M1_AWREADY(M1_AWREADY),
    .M1_WDATA  (M1_WDATA),
    .M1_WSTRB  (M1_WSTRB),
    .M1_WLAST  (M1_WLAST),
    .M1_WVALID (M1_WVALID),
    .M1_WREADY (M1_WREADY),
    .M1_BRESP  (M1_BRESP),
    .M1_BVALID (M1_BVALID),
    .M1_BREADY (M1_BREADY),
    .M1_ARADDR (M1_ARADDR),
    .M1_ARLEN  (M1_ARLEN),
    .M1_ARSIZE (M1_ARSIZE),
    .M1_ARBURST(M1_ARBURST),
    .M1_ARVALID(M1_ARVALID),
    .M1_ARREADY(M1_ARREADY),
    .M1_RDATA  (M1_RDATA),
    .M1_RRESP  (M1_RRESP),
    .M1_RLAST  (M1_RLAST),
    .M1_RVALID (M1_RVALID),
    .M1_RREADY (M1_RREADY),

    // Slave 0
    .S0_AWADDR (S0_AWADDR),
    .S0_AWLEN  (S0_AWLEN),
    .S0_AWSIZE (S0_AWSIZE),
    .S0_AWBURST(S0_AWBURST),
    .S0_AWVALID(S0_AWVALID),
    .S0_AWREADY(S0_AWREADY),
    .S0_WDATA  (S0_WDATA),
    .S0_WSTRB  (S0_WSTRB),
    .S0_WLAST  (S0_WLAST),
    .S0_WVALID (S0_WVALID),
    .S0_WREADY (S0_WREADY),
    .S0_BRESP  (S0_BRESP),
    .S0_BVALID (S0_BVALID),
    .S0_BREADY (S0_BREADY),
    .S0_ARADDR (S0_ARADDR),
    .S0_ARLEN  (S0_ARLEN),
    .S0_ARSIZE (S0_ARSIZE),
    .S0_ARBURST(S0_ARBURST),
    .S0_ARVALID(S0_ARVALID),
    .S0_ARREADY(S0_ARREADY),
    .S0_RDATA  (S0_RDATA),
    .S0_RRESP  (S0_RRESP),
    .S0_RLAST  (S0_RLAST),
    .S0_RVALID (S0_RVALID),
    .S0_RREADY (S0_RREADY),

    // Slave 1
    .S1_AWADDR (S1_AWADDR),
    .S1_AWLEN  (S1_AWLEN),
    .S1_AWSIZE (S1_AWSIZE),
    .S1_AWBURST(S1_AWBURST),
    .S1_AWVALID(S1_AWVALID),
    .S1_AWREADY(S1_AWREADY),
    .S1_WDATA  (S1_WDATA),
    .S1_WSTRB  (S1_WSTRB),
    .S1_WLAST  (S1_WLAST),
    .S1_WVALID (S1_WVALID),
    .S1_WREADY (S1_WREADY),
    .S1_BRESP  (S1_BRESP),
    .S1_BVALID (S1_BVALID),
    .S1_BREADY (S1_BREADY),
    .S1_ARADDR (S1_ARADDR),
    .S1_ARLEN  (S1_ARLEN),
    .S1_ARSIZE (S1_ARSIZE),
    .S1_ARBURST(S1_ARBURST),
    .S1_ARVALID(S1_ARVALID),
    .S1_ARREADY(S1_ARREADY),
    .S1_RDATA  (S1_RDATA),
    .S1_RRESP  (S1_RRESP),
    .S1_RLAST  (S1_RLAST),
    .S1_RVALID (S1_RVALID),
    .S1_RREADY (S1_RREADY),

    // Slave 2
    .S2_AWADDR (S2_AWADDR),
    .S2_AWLEN  (S2_AWLEN),
    .S2_AWSIZE (S2_AWSIZE),
    .S2_AWBURST(S2_AWBURST),
    .S2_AWVALID(S2_AWVALID),
    .S2_AWREADY(S2_AWREADY),
    .S2_WDATA  (S2_WDATA),
    .S2_WSTRB  (S2_WSTRB),
    .S2_WLAST  (S2_WLAST),
    .S2_WVALID (S2_WVALID),
    .S2_WREADY (S2_WREADY),
    .S2_BRESP  (S2_BRESP),
    .S2_BVALID (S2_BVALID),
    .S2_BREADY (S2_BREADY),
    .S2_ARADDR (S2_ARADDR),
    .S2_ARLEN  (S2_ARLEN),
    .S2_ARSIZE (S2_ARSIZE),
    .S2_ARBURST(S2_ARBURST),
    .S2_ARVALID(S2_ARVALID),
    .S2_ARREADY(S2_ARREADY),
    .S2_RDATA  (S2_RDATA),
    .S2_RRESP  (S2_RRESP),
    .S2_RLAST  (S2_RLAST),
    .S2_RVALID (S2_RVALID),
    .S2_RREADY (S2_RREADY),

    // Slave 3
    .S3_AWADDR (S3_AWADDR),
    .S3_AWLEN  (S3_AWLEN),
    .S3_AWSIZE (S3_AWSIZE),
    .S3_AWBURST(S3_AWBURST),
    .S3_AWVALID(S3_AWVALID),
    .S3_AWREADY(S3_AWREADY),
    .S3_WDATA  (S3_WDATA),
    .S3_WSTRB  (S3_WSTRB),
    .S3_WLAST  (S3_WLAST),
    .S3_WVALID (S3_WVALID),
    .S3_WREADY (S3_WREADY),
    .S3_BRESP  (S3_BRESP),
    .S3_BVALID (S3_BVALID),
    .S3_BREADY (S3_BREADY),
    .S3_ARADDR (S3_ARADDR),
    .S3_ARLEN  (S3_ARLEN),
    .S3_ARSIZE (S3_ARSIZE),
    .S3_ARBURST(S3_ARBURST),
    .S3_ARVALID(S3_ARVALID),
    .S3_ARREADY(S3_ARREADY),
    .S3_RDATA  (S3_RDATA),
    .S3_RRESP  (S3_RRESP),
    .S3_RLAST  (S3_RLAST),
    .S3_RVALID (S3_RVALID),
    .S3_RREADY (S3_RREADY)
);

endmodule


