library verilog;
use verilog.vl_types.all;
entity AXI_Master_Aggregator is
    generic(
        ADDR_WIDTH      : integer := 32;
        DATA_WIDTH      : integer := 32;
        NUM_MASTERS     : integer := 3
    );
    port(
        ACLK            : in     vl_logic;
        ARESETN         : in     vl_logic;
        M0_ARADDR       : in     vl_logic_vector;
        M0_ARPROT       : in     vl_logic_vector(2 downto 0);
        M0_ARVALID      : in     vl_logic;
        M0_ARREADY      : out    vl_logic;
        M0_RDATA        : out    vl_logic_vector;
        M0_RRESP        : out    vl_logic_vector(1 downto 0);
        M0_RVALID       : out    vl_logic;
        M0_RREADY       : in     vl_logic;
        M0_AWADDR       : in     vl_logic_vector;
        M0_AWPROT       : in     vl_logic_vector(2 downto 0);
        M0_AWVALID      : in     vl_logic;
        M0_AWREADY      : out    vl_logic;
        M0_WDATA        : in     vl_logic_vector;
        M0_WSTRB        : in     vl_logic_vector;
        M0_WVALID       : in     vl_logic;
        M0_WREADY       : out    vl_logic;
        M0_BRESP        : out    vl_logic_vector(1 downto 0);
        M0_BVALID       : out    vl_logic;
        M0_BREADY       : in     vl_logic;
        M1_ARADDR       : in     vl_logic_vector;
        M1_ARPROT       : in     vl_logic_vector(2 downto 0);
        M1_ARVALID      : in     vl_logic;
        M1_ARREADY      : out    vl_logic;
        M1_RDATA        : out    vl_logic_vector;
        M1_RRESP        : out    vl_logic_vector(1 downto 0);
        M1_RVALID       : out    vl_logic;
        M1_RREADY       : in     vl_logic;
        M1_AWADDR       : in     vl_logic_vector;
        M1_AWPROT       : in     vl_logic_vector(2 downto 0);
        M1_AWVALID      : in     vl_logic;
        M1_AWREADY      : out    vl_logic;
        M1_WDATA        : in     vl_logic_vector;
        M1_WSTRB        : in     vl_logic_vector;
        M1_WVALID       : in     vl_logic;
        M1_WREADY       : out    vl_logic;
        M1_BRESP        : out    vl_logic_vector(1 downto 0);
        M1_BVALID       : out    vl_logic;
        M1_BREADY       : in     vl_logic;
        M2_ARADDR       : in     vl_logic_vector;
        M2_ARPROT       : in     vl_logic_vector(2 downto 0);
        M2_ARVALID      : in     vl_logic;
        M2_ARREADY      : out    vl_logic;
        M2_RDATA        : out    vl_logic_vector;
        M2_RRESP        : out    vl_logic_vector(1 downto 0);
        M2_RVALID       : out    vl_logic;
        M2_RREADY       : in     vl_logic;
        M2_AWADDR       : in     vl_logic_vector;
        M2_AWPROT       : in     vl_logic_vector(2 downto 0);
        M2_AWVALID      : in     vl_logic;
        M2_AWREADY      : out    vl_logic;
        M2_WDATA        : in     vl_logic_vector;
        M2_WSTRB        : in     vl_logic_vector;
        M2_WVALID       : in     vl_logic;
        M2_WREADY       : out    vl_logic;
        M2_BRESP        : out    vl_logic_vector(1 downto 0);
        M2_BVALID       : out    vl_logic;
        M2_BREADY       : in     vl_logic;
        M_ARADDR        : out    vl_logic_vector;
        M_ARPROT        : out    vl_logic_vector(2 downto 0);
        M_ARVALID       : out    vl_logic;
        M_ARREADY       : in     vl_logic;
        M_RDATA         : in     vl_logic_vector;
        M_RRESP         : in     vl_logic_vector(1 downto 0);
        M_RVALID        : in     vl_logic;
        M_RREADY        : out    vl_logic;
        M_AWADDR        : out    vl_logic_vector;
        M_AWPROT        : out    vl_logic_vector(2 downto 0);
        M_AWVALID       : out    vl_logic;
        M_AWREADY       : in     vl_logic;
        M_WDATA         : out    vl_logic_vector;
        M_WSTRB         : out    vl_logic_vector;
        M_WVALID        : out    vl_logic;
        M_WREADY        : in     vl_logic;
        M_BRESP         : in     vl_logic_vector(1 downto 0);
        M_BVALID        : in     vl_logic;
        M_BREADY        : out    vl_logic
    );
    attribute mti_svvh_generic_type : integer;
    attribute mti_svvh_generic_type of ADDR_WIDTH : constant is 1;
    attribute mti_svvh_generic_type of DATA_WIDTH : constant is 1;
    attribute mti_svvh_generic_type of NUM_MASTERS : constant is 1;
end AXI_Master_Aggregator;
